# SPDX-FileCopyrightText: 2026 IObundle, Lda
#
# SPDX-License-Identifier: MIT
#
# Py2HWSW Version 0.81 has generated this code (https://github.com/IObundle/py2hwsw).


#This file was auto generated by gen_custom_config_build.py

### Set Ethernet environment variables
#Eth interface address of pc connected to ethernet peripheral (based on board name)
$(if $(findstring sim,$(MAKECMDGOALS))$(SIMULATOR),$(eval BOARD=))
ifeq ($(BOARD),iob_aes_ku040_db_g)
ETH_IF ?=eno1
endif
ifeq ($(BOARD),iob_cyclonev_gt_dk)
ETH_IF ?= enp0s31f6
endif
# Set a MAC address for console (randomly generated)
RMAC_ADDR ?= 989096c0632c
export RMAC_ADDR
#Set correct environment if running on IObundle machines
ifneq ($(filter feynman pudim-flan sericaia,$(shell hostname)),)
IOB_CONSOLE_PYTHON_ENV ?= /opt/pyeth3/bin/python
else
IOB_CONSOLE_PYTHON_ENV ?= $(ROOT_DIR)/scripts/pyRawWrapper/pyRawWrapper
endif
