/*
 * SPDX-FileCopyrightText: 2026 IObundle, Lda
 *
 * SPDX-License-Identifier: MIT
 *
 * Py2HWSW Version 0.81.0 has generated this code
 * (https://github.com/IObundle/py2hwsw).
 */

#ifndef H_IOB_REGFILEIF_INVERTED_CSRS_CONF_H
#define H_IOB_REGFILEIF_INVERTED_CSRS_CONF_H

#define IOB_REGFILEIF_INVERTED_CSRS_ADDR_W 6
#define IOB_REGFILEIF_INVERTED_CSRS_DATA_W 32
#define IOB_REGFILEIF_INVERTED_CSRS_START_ADDR 0
#define IOB_REGFILEIF_INVERTED_CSRS_START_W 8
#define IOB_REGFILEIF_INVERTED_CSRS_DONE_ADDR 1
#define IOB_REGFILEIF_INVERTED_CSRS_DONE_W 8
#define IOB_REGFILEIF_INVERTED_CSRS_METAMODEL_ADDR_ADDR 4
#define IOB_REGFILEIF_INVERTED_CSRS_METAMODEL_ADDR_W 32
#define IOB_REGFILEIF_INVERTED_CSRS_OUTPUT_ADDR_ADDR 8
#define IOB_REGFILEIF_INVERTED_CSRS_OUTPUT_ADDR_W 32
#define IOB_REGFILEIF_INVERTED_CSRS_TEMP_ADDR_ADDR 12
#define IOB_REGFILEIF_INVERTED_CSRS_TEMP_ADDR_W 32
#define IOB_REGFILEIF_INVERTED_CSRS_MODEL_ADDR_ADDR 16
#define IOB_REGFILEIF_INVERTED_CSRS_MODEL_ADDR_W 32
#define IOB_REGFILEIF_INVERTED_CSRS_CORRECTOUTPUTS_ADDR_ADDR 20
#define IOB_REGFILEIF_INVERTED_CSRS_CORRECTOUTPUTS_ADDR_W 32
#define IOB_REGFILEIF_INVERTED_CSRS_INPUTSVECTOR_ADDR_ADDR 24
#define IOB_REGFILEIF_INVERTED_CSRS_INPUTSVECTOR_ADDR_W 32
#define IOB_REGFILEIF_INVERTED_CSRS_RST_ADDR 28
#define IOB_REGFILEIF_INVERTED_CSRS_RST_W 8
#define IOB_REGFILEIF_INVERTED_CSRS_VERSION_ADDR 32
#define IOB_REGFILEIF_INVERTED_CSRS_VERSION_W 32
#define IOB_REGFILEIF_INVERTED_CSRS_VERSION 0x008100

#endif // H_IOB_REGFILEIF_INVERTED_CSRS_CONF_H
