/*
 * SPDX-FileCopyrightText: 2026 IObundle, Lda
 *
 * SPDX-License-Identifier: MIT
 *
 * Py2HWSW Version 0.81.0 has generated this code
 * (https://github.com/IObundle/py2hwsw).
 */

#ifndef H_IOB_REGFILEIF_INVERTED_CSRS_CSRS_H
#define H_IOB_REGFILEIF_INVERTED_CSRS_CSRS_H

/** @file iob_regfileif_inverted_csrs.h
 *  @brief Function prototypes for the iob_regfileif_inverted core.
 *
 *  This file contains the function prototypes to access the Control and Status
 * Registers (CSRs) for the iob_regfileif_inverted core.
 *
 *  This file is automatically generated by Py2HWSW
 */

#include <stdint.h>

#include "iob_regfileif_inverted_csrs_conf.h"

// Base Address
/**
 * @brief Set core base address.
 *
 * This function sets the base address for the core in the system. All other
 * accesses are offset from this base address.
 *
 * @param addr Base address for core.
 */
void iob_regfileif_inverted_csrs_init_baseaddr(uint32_t addr);

// IO read and write function prototypes
/**
 * @brief Write access function prototype.
 *
 * @param addr Address to write to.
 * @param data_w Data width in bits.
 * @param value Value to write.
 */
void iob_write(uint32_t addr, uint32_t data_w, uint32_t value);
/**
 * @brief Read access function prototype.
 *
 * @param addr Address to write to.
 * @param data_w Data width in bits.
 * @return uint32_t Read data value.
 */
uint32_t iob_read(uint32_t addr, uint32_t data_w);

// Core Setters and Getters
/**
 * @brief Set start value.
 * Set 1 to start. versat_ai sets this to 0 to acknowledge start received
 * @param value start Value.
 */
void iob_regfileif_inverted_csrs_set_start(uint8_t value);
/**
 * @brief Get start value.
 * Set 1 to start. versat_ai sets this to 0 to acknowledge start received
 * @return uint8_t start value.
 */
uint8_t iob_regfileif_inverted_csrs_get_start();
/**
 * @brief Set done value.
 * Set to 1 by versat_ai when finished. 0 while running
 * @param value done Value.
 */
void iob_regfileif_inverted_csrs_set_done(uint8_t value);
/**
 * @brief Get metamodel_addr value.
 * Metamodel address
 * @return uint32_t metamodel_addr value.
 */
uint32_t iob_regfileif_inverted_csrs_get_metamodel_addr();
/**
 * @brief Get output_addr value.
 * Model address
 * @return uint32_t output_addr value.
 */
uint32_t iob_regfileif_inverted_csrs_get_output_addr();
/**
 * @brief Get temp_addr value.
 * Model address
 * @return uint32_t temp_addr value.
 */
uint32_t iob_regfileif_inverted_csrs_get_temp_addr();
/**
 * @brief Get model_addr value.
 * Model address
 * @return uint32_t model_addr value.
 */
uint32_t iob_regfileif_inverted_csrs_get_model_addr();
/**
 * @brief Get correctOutputs_addr value.
 * Correct output address
 * @return uint32_t correctOutputs_addr value.
 */
uint32_t iob_regfileif_inverted_csrs_get_correctOutputs_addr();
/**
 * @brief Get inputsVector_addr value.
 * Inputs address
 * @return uint32_t inputsVector_addr value.
 */
uint32_t iob_regfileif_inverted_csrs_get_inputsVector_addr();
/**
 * @brief Get rst value.
 * Resets CPU (1) or not (0).
 * @return uint8_t rst value.
 */
uint8_t iob_regfileif_inverted_csrs_get_rst();
/**
 * @brief Get version value.
 * Product version in SemVer format. This 24-bit register uses nibbles to
 * represent decimal numbers using their binary values. The two most significant
 * nibbles represent the major part of the version, followed by two nibbles that
 * represent the minor part. The two least significant nibbles represent the
 * patch version. For example V12.34.56 is represented by 0x123456.
 * @return uint32_t version value.
 */
uint32_t iob_regfileif_inverted_csrs_get_version();

#endif // H_IOB_REGFILEIF_INVERTED_CSRS__CSRS_H
