#pragma once
#define VERSAT_AI_OUTPUT_SIZE 40
#define VERSAT_AI_TEMP_SIZE 60416
#define VERSAT_AI_MODEL_SIZE 24008
#define VERSAT_AI_CORRECT_SIZE 131536
#define VERSAT_AI_N_INPUTS 1
#define VERSAT_AI_INPUT_0_SIZE 3136
#define VERSAT_AI_ALL_INPUTS_SIZE 3136
const int VERSAT_AI_INPUT_OFFSET[] = {0};
