#pragma once
#define VERSAT_AI_OUTPUT_SIZE 32
#define VERSAT_AI_TEMP_SIZE 0
#define VERSAT_AI_MODEL_SIZE 0
#define VERSAT_AI_CORRECT_SIZE 32
#define VERSAT_AI_N_INPUTS 2
#define VERSAT_AI_INPUT_0_SIZE 32
#define VERSAT_AI_INPUT_1_SIZE 32
#define VERSAT_AI_ALL_INPUTS_SIZE 64
const int VERSAT_AI_INPUT_OFFSET[] = {0, 32};
