#include "versat_private.h"

#include <math.h>
#include <stdbool.h>
#include <stdint.h>

#define exit(...) ((void)0)
void clear_cache();

#define MIN(A, B) ((A < B ? A : B))
#define MAX(A, B) ((A > B ? A : B))

// Care when using this, when not debugging this just crashes the program
#define DEBUG_BREAK() __asm__("int3")

void *Software_ConvWithBias(void *inputX, void *inputW, void *inputB,
                            void *output, int index, ConvInfo *info) {
  int batchSize = info->inputDims[0];
  int inChannels = info->inputDims[1];
  int inW = info->inputDims[3];
  int inH = info->inputDims[2];

  int strideW = info->strideDims[1];
  int strideH = info->strideDims[0];

  int featureMaps = info->featureMaps;

  int kernelW = info->kernelDims[1];
  int kernelH = info->kernelDims[0];

  int group = info->group;

  int outChannels = info->outputDims[1]; // Should be equal to feature maps.
  int outW = info->outputDims[3];
  int outH = info->outputDims[2];

  float *input = (float *)inputX;
  float *kernel = (float *)inputW;
  float *bias = (float *)inputB;
  float *outView = (float *)output;

  ExtraInfo extra = CalculateExtraInfo_Conv(info);

  AddressGen outGenInst =
      StartAddress(info->outputDims, info->outputDims, info->dims);
  AddressGen *outGen = &outGenInst;

  // We probably want to move this to the array generated by python.
  // Emit the proper array directly
  int stride[MAX_DIMS];
  stride[0] = 1;
  stride[1] = 1;
  for (int i = 0; i < info->strideSize; i++) {
    stride[i + 2] = info->strideDims[i];
  }

  int offset[MAX_DIMS];
  offset[0] = 0;
  offset[1] = 0;
  offset[2] = extra.leftPadH;
  offset[3] = extra.leftPadW;

  int inputSize = inW * inH * inChannels;
  int outputSize = outW * outH * outChannels;

  float *inputView = input; // + (batch * inputSize);

  for (; Address_IsValid(outGen); Address_Advance(outGen)) {
    int outPos = Address_GetValue(outGen);

    AddressGen inputPos = Address_Map2(outGen, info->inputDims, stride, offset);

    // KernelGen does not know about the indexes used to access the kernel
    // weights We compute them outside.
    int outC = outGen->addressVars[1];

    float accum = 0.0f;
    KernelGen kernInst = StartKernel(&inputPos, info->kernelDims, 2);
    KernelGen *kern = &kernInst;

    int inChannelsPerGroup = inChannels / group;
    int outChannelsPerGroup = outChannels / group;

    if (group == 1) {
      kern->addressGenVars[1] = 0;
    } else {
      kern->addressGenVars[1] =
          (outC / outChannelsPerGroup) * inChannelsPerGroup;
    }
    kern->kernelDims[1] = inChannels / group;

    int currentGroup = outC / outChannelsPerGroup;
    for (int inC = currentGroup * inChannelsPerGroup;
         inC < (currentGroup + 1) * inChannelsPerGroup; inC++) {
      int kernelIndex =
          outC * (inChannels / group) * extra.kernelW * extra.kernelH;

      for (; Kernel_IsValid(kern); Kernel_Advance(kern), kernelIndex += 1) {
        bool isPadded = Kernel_IsInsidePad(kern);
        if (isPadded) {
          continue;
        }
        int index = Kernel_GetValue(kern);

        float kernelVal = kernel[kernelIndex];
        float inputVal = inputView[index];
        accum += inputVal * kernelVal;
      }
    }

    if (bias) {
      outView[outPos] = accum + bias[outC];
    } else {
      outView[outPos] = accum;
    }
  }

  return output;
}

void *Software_Conv(void *inputX, void *inputW, void *output, int index,
                    ConvInfo *info) {
  return Software_ConvWithBias(inputX, inputW, NULL, output, index, info);
}

void *Software_Reshape(void *data, void *shape, void *output, int index,
                       ReshapeInfo *info) {
  // TODO: Need to copy the input, cannot assume that memory will remain valid.
  // NOTE: If we want to avoid the copy need to put logic on onnx script that
  // removes the operator call.
  return data;
}

void *Software_Transpose(void *data, void *output, int index,
                         TransposeInfo *info) {
  int64_t *perms = (int64_t *)info->perm;

  int64_t outDims[MAX_DIMS] = {};

  for (int i = 0; i < info->numberInputDims; i++) {
    int index = info->perm[i];
    outDims[i] = info->inputDims[index];
  }

  AddressGen in =
      StartAddress(info->inputDims, info->inputDims, info->numberInputDims);
  AddressGen out = StartAddress(outDims, outDims, info->numberInputDims);

  float *inView = (float *)data;
  float *outView = (float *)output;

  for (; Address_IsValid(&in); Address_Advance(&in)) {
    int inAddr = Address_GetValue(&in);

    for (int i = 0; i < info->numberInputDims; i++) {
      int index = info->perm[i];
      out.addressVars[i] = in.addressVars[index];
    }

    int outAddr = Address_GetValue(&out);

    outView[outAddr] = inView[inAddr];
  }

  return output;
}

void *Software_Add(void *inputA, void *inputB, void *output, int index,
                   AddInfo *info) {
  float *viewA = (float *)inputA;
  float *viewB = (float *)inputB;
  float *out = (float *)output;

  // TODO: Instead of stuffing addressGen with the broadcasting stuff, we could
  // just iterate the broadcasted shape and call a function that would return
  // the proper index for the non broadcasted shape.
  //       Basically pull out all the properDim logic from address gen into a
  //       extra function.

  AddressGen inA =
      StartAddress(info->broadCastedShape, info->firstInputDim, info->maxDims);
  AddressGen inB =
      StartAddress(info->broadCastedShape, info->secondInputDim, info->maxDims);
  AddressGen outGen = StartAddress(info->broadCastedShape,
                                   info->broadCastedShape, info->maxDims);

  while (Address_IsValid(&outGen)) {
    int indexA = Address_GetValue(&inA);
    int indexB = Address_GetValue(&inB);
    int indexO = Address_GetValue(&outGen);

    Address_Advance(&inA);
    Address_Advance(&inB);
    Address_Advance(&outGen);

    float valA = viewA[indexA];
    float valB = viewB[indexB];

    out[indexO] = valA + valB;
  }

  return output;
}

void *Software_Relu(void *inputX, void *output, int index, ReluInfo *info) {
  float *view = (float *)inputX;
  float *out = (float *)output;

  int64_t totalSize = CalculateSizeOfDim(info->inputDims, info->dims);

  for (int64_t i = 0; i < totalSize; i++) {
    float val = view[i];
    out[i] = MAX(0.0f, val);
  }

  return output;
}

#if 0

// First need to generate the addresses that we care about, including padding and such.
// Generate from the perspective of the output.

#endif

void *Software_MaxPool(void *inputX, void *output, int index,
                       MaxPoolInfo *info) {
  float *view = (float *)inputX;
  float *out = (float *)output;

  ExtraInfo extra = CalculateExtraInfo_MaxPool(info);

  AddressGen outGenInst =
      StartAddress(info->outputDims, info->outputDims, info->dims);
  AddressGen *outGen = &outGenInst;

  // We probably want to move this to the array generated by python.
  // Emit the proper array directly
  int stride[MAX_DIMS];
  stride[0] = 1;
  stride[1] = 1;
  for (int i = 0; i < info->strideSize; i++) {
    stride[i + 2] = info->strideDims[i];
  }

  int offset[MAX_DIMS];
  offset[0] = 0;
  offset[1] = 0;
  offset[2] = extra.leftPadH;
  offset[3] = extra.leftPadW;

  // MARK
  for (; Address_IsValid(outGen); Address_Advance(outGen)) {
    float max = 0.0f;
    bool firstSet = false;

    AddressGen inputPos = Address_Map2(outGen, info->inputDims, stride, offset);
    KernelGen kernInst = StartKernel(&inputPos, info->kernelDims, 2);
    KernelGen *kern = &kernInst;

    for (; Kernel_IsValid(kern); Kernel_Advance(kern)) {
      bool isPadded = Kernel_IsInsidePad(kern);
      if (isPadded) {
        continue;
      }
      int index = Kernel_GetValue(kern);

      float val = view[index];

      // NOTE: Padding should never affect the output value.
      //       Because negative values exist, we cannot just use zero to
      //       represent a padded value. We might get away with using -inf, but
      //       for now we just use an extra flag to check validity.
      if (!firstSet) {
        max = val;
        firstSet = true;
      } else {
        max = MAX(max, val);
      }
    }

    int outputIndex = Address_GetValue(outGen);
    out[outputIndex] = max;
  }

  return output;
}

// NOTE: Basically a copy of MaxPool but changed to calculate the average at the
// end.
void *Software_AveragePool(void *inputX, void *output, int index,
                           AveragePoolInfo *info) {
  float *view = (float *)inputX;
  float *out = (float *)output;

  ExtraInfo extra = CalculateExtraInfo_AveragePool(info);

  AddressGen outGenInst =
      StartAddress(info->outputDims, info->outputDims, info->dims);
  AddressGen *outGen = &outGenInst;

  // We probably want to move this to the array generated by python.
  // Emit the proper array directly
  int stride[MAX_DIMS];
  stride[0] = 1;
  stride[1] = 1;
  for (int i = 0; i < info->strideSize; i++) {
    stride[i + 2] = info->strideDims[i];
  }

  int offset[MAX_DIMS];
  offset[0] = 0;
  offset[1] = 0;
  offset[2] = extra.leftPadH;
  offset[3] = extra.leftPadW;

  for (; Address_IsValid(outGen); Address_Advance(outGen)) {
    float sum = 0.0f;
    float div = 0.0f;

    AddressGen inputPos = Address_Map2(outGen, info->inputDims, stride, offset);
    KernelGen kernInst = StartKernel(&inputPos, info->kernelDims, 2);
    KernelGen *kern = &kernInst;
    for (; Kernel_IsValid(kern); Kernel_Advance(kern)) {
      if (Kernel_IsInsidePad(kern)) {
        continue;
      }
      int index = Kernel_GetValue(kern);

      float val = view[index];

      sum += val;
      div += 1.0f;
    }

    int outputIndex = Address_GetValue(outGen);
    out[outputIndex] = (sum / div);
  }

  return output;
}

void *Software_MatMul(void *inputA, void *inputB, void *output, int index,
                      MatMulInfo *info) {
  float *viewA = (float *)inputA;
  float *viewB = (float *)inputB;
  float *viewOut = (float *)output;

  int AH = info->inputADims[0];
  int AW = info->inputADims[1];

  int BH = info->inputBDims[0];
  int BW = info->inputBDims[1];

  int OH = info->outputDims[0];
  int OW = info->outputDims[1];

  if (AW != BH) {
    versat_printf("Something very wrong is happening in MatMul\n");
  }

  for (int y = 0; y < OH; y++) {
    for (int x = 0; x < OW; x++) {
      int indexOut = y * OW + x;

      viewOut[indexOut] = 0.0f;
      for (int c = 0; c < AW; c++) {
        int indexA = y * AW + c;
        int indexB = c * BW + x;

        float valA = viewA[indexA];
        float valB = viewB[indexB];

        viewOut[indexOut] += valA * valB;
      }
    }
  }

  return output;
}

double ABS(double x) { return x < 0 ? -x : x; }

double my_exp(double x) {
  double result = 1.0;
  double term = 1.0;
  double div = 1.0;
  double dx = (double)x;
  int maxTerms = 100000; // Failsafe

  double lastResult = result;
  for (int n = 1; n < maxTerms; n++) {
    term *= dx / div;
    div += 1.0;
    result += term;

    // As term gets smaller eventually we will reach a point where addition does
    // not change anything
    if (lastResult == result) {
      break;
    }
    lastResult = result;
  }

  return result;
}

#define MAX_ITERS 20
double thetah_table[MAX_ITERS] = {
    0.549306, 0.255413, 0.125657, 0.062582, 0.031260, 0.015626, 0.007813,
    0.003906, 0.001953, 0.000977, 0.000488, 0.000244, 0.000122, 0.000061,
    0.000031, 0.000015, 0.000008, 0.000004, 0.000002, 0.000001};

double Cordic_arctanh(double y, double x) {
  double angle = 0.0;
  double P2i = 0.5;
  int k = 4;

  for (int i = 1; i < MAX_ITERS; i++) {
    double arc_tangent = thetah_table[i - 1];

    int iters = 1;
    if (i == k) {
      iters = 2;
      k = (3 * k) + 1;
    }

    for (int k = 0; k < iters; k++) {
      double sigma = 1.0;
      if (y < 0) {
        sigma = -1.0;
      }

      angle = angle + sigma * arc_tangent;
      double calcX = x - sigma * y * P2i;
      double calcY = y - sigma * x * P2i;

      x = calcX;
      y = calcY;
    }

    P2i /= 2.0;
  }

  return angle;
}

#define MATH_E 2.71828182846
#define MATH_PI 3.14159265359

double Cordic_log(double in) {
  double val = in;

  double extra = 0;
  while (val > MATH_E) {
    val /= MATH_E;
    extra += 1;
  }

  while (val < 1.0f) {
    val *= MATH_E;
    extra -= 1;
  }

  double res = (2.0 * Cordic_arctanh(val - 1, val + 1)) + extra;
  return res;
}

double Cordic_exp(double exponent) {
  int k = 4;
  double angle = exponent;
  double y = 1.207497067763;
  double x = 1.207497067763;
  double P2i = 0.5;

  int extra = 0;
  while (angle > 1.0) {
    angle -= 1.0;
    extra += 1;
  }

  while (angle < 0) {
    angle += 1.0;
    extra -= 1;
  }

  for (int i = 1; i < MAX_ITERS; i++) {
    double arc_tangent = thetah_table[i - 1];

    int iters = 1;
    if (i == k) {
      iters = 2;
      k = (3 * k) + 1;
    }

    for (int k = 0; k < iters; k++) {
      double sigma = 1.0;
      if (angle > 0.0) {
        sigma = -1.0;
      }

      angle = angle + sigma * arc_tangent;
      double calcX = x - sigma * y * P2i;
      double calcY = y - sigma * x * P2i;

      x = calcX;
      y = calcY;
    }

    P2i /= 2.0;
  }

  for (int i = 0; i < extra; i++) {
    x *= MATH_E;
  }
  for (int i = 0; i > extra; i--) {
    x /= MATH_E;
  }

  return x;
}

double my_log(double x) {
  double start = 0.0;

  for (int i = 0; i < 1000; i++) {
    double last = start;
    start = start + 2.0 * ((x - my_exp(start)) / (x + my_exp(start)));
    if (last == start) {
      break;
    }
  }

  return start;
}

double my_pow(double b, double e) {
  double result = my_exp(e * my_log(b));
  return result;
}

double Cordic_pow(double b, double e) {
  double result = Cordic_exp(e * Cordic_log(b));
  return result;
}

#if 1
typedef uint32_t u32;
typedef int32_t i32;

typedef uint8_t u8;

typedef struct {
  u32 mantissa : 23;
  u32 exponent : 8;
  u32 sign : 1;
} PackedFP;

typedef struct {
  u32 mantissa;
  i32 exponent;
  u8 sign;
} UnpackedFP;

UnpackedFP Unpack(float f, bool addImplicitBit) {
  PackedFP fp = *((PackedFP *)&f);

  UnpackedFP res = {};
  res.mantissa = fp.mantissa;

  if (addImplicitBit) {
    res.mantissa |= (1 << 23);
  }

  res.exponent = -127 + fp.exponent;
  res.sign = fp.sign;

  return res;
}

float Pack(UnpackedFP fp) {
  PackedFP res = {};
  res.sign = fp.sign;
  res.exponent = fp.exponent + 127;
  res.mantissa = fp.mantissa & ((1 << 24) - 1);

  return *((float *)&res);
}

static inline int Clamp(int min, int val, int max) {
  if (val < min) {
    return min;
  }
  if (val > max) {
    return max;
  }
  return val;
}

u32 Downsize(float f, int totalSize, int exponentAmount) {
  UnpackedFP unpacked = Unpack(f, false);

  int mantissaAmount = totalSize - 1 - exponentAmount;
  int signPos = totalSize - 1;

  u32 sign = (unpacked.sign) ? 1 : 0;

  int bias = (((1 << exponentAmount) / 2) - 1);

  u32 trueMantissa = Clamp(0, unpacked.mantissa >> (23 - mantissaAmount),
                           (1 << mantissaAmount) - 1);
  u32 trueExponent = Clamp(0, unpacked.exponent + (bias - 1), 31) &
                     ((1 << exponentAmount) - 1);

  u32 res =
      (trueMantissa | (trueExponent << mantissaAmount) | (sign << signPos));

  if (res >= (1 << totalSize)) {
    versat_printf("ERROR\n");
  }

  return res;
}

float Upsize(u32 in, int totalSize, int exponentAmount) {
  int mantissaAmount = totalSize - 1 - exponentAmount;

  u32 mantissaMask = ((1 << mantissaAmount) - 1);
  u32 exponentMask = ((1 << exponentAmount) - 1);

  u32 exponent = ((in >> mantissaAmount) & exponentMask);
  u32 mantissa = (in & mantissaMask) << (23 - mantissaAmount);
  int sign = ((in) >> (totalSize - 1)) & 1;

  bool subnormal = (exponent == 0);

  int bias = (((1 << exponentAmount) / 2) - 1);

  UnpackedFP unpacked = {};
  unpacked.sign = sign;
  unpacked.exponent = exponent - (bias - 1);
  unpacked.mantissa = mantissa;

  return Pack(unpacked);
}

static float expTable[128];
static float mantissaTable[1 << 16];

// static float expTable[1 << 16];
int table_totalSize = 16;
int table_exponent = 5;

/*
exp(1.024651) = 2.78612293397
exp(-0.973167) = 0.37788438119
exp(1.024651) = 2.78612293397
exp(-0.973167) = 0.37788438119
*/

float Table_exp(float in) {
  int asInt = (int)in;

  float mantissa = in - ((float)asInt);

  int expOffset = 63;

  // versat_printf("%08x %08x\n",*(u32*) &in,*(u32*) &mantissa);

  if (mantissa < 0.0f) {
    mantissa += 1.0f;
    expOffset = 62;
  }

  u32 mantissaPartU32 = *((u32 *)&mantissa);

  u32 mantissaIndex = ((mantissaPartU32)&0x1FFF8000) >> 15;

  u32 expIndex = asInt + expOffset;

  // versat_printf("%08x %f %d
  // %d\n",mantissaPartU32,mantissa,expIndex,mantissaIndex);

  float mantissaPart = mantissaTable[mantissaIndex];
  float expPart = expTable[expIndex];

  float res = expPart * mantissaPart;

  // versat_printf("%f %f %f %f\n",in,expPart,mantissaPart,res);

  return res;

#if 0
  u32 index = Downsize(in,table_totalSize,table_exponent);

  float approxExp = expTable[index];
  float trueExp = Cordic_exp(in);

  versat_printf("%f %f %f %f\n",in,approxExp,trueExp,trueExp - approxExp);
#endif
}

void PrintBinary(u32 val) {
  for (int i = 31; i >= 0; i--) {
    u32 v = (val) & (1 << i);
    if (v) {
      versat_printf("1");
    } else {
      versat_printf("0");
    }
  }

  versat_printf("\n");
}

void InitializeExpTable() {
  static bool init = false;

  if (init) {
    return;
  }
  init = true;

#if 0
  for(u32 i = 0; i < (1 << table_totalSize); i++){
    float asF = Upsize(i,table_totalSize,table_exponent);

    expTable[i] = Cordic_exp(asF);  
  }
#endif

  float f = -63.0f;
  for (int i = 0; f < 64.0f; i += 1, f += 1.0f) {
    int asInt = (int)f;
    int index = asInt + 63;
    expTable[index] = Cordic_exp(f);
  }

  u32 start = 0x20000000;
  u32 incr = 0x00008000;
  u32 max = 0x3f7fe000;

  int index = 0;
  for (u32 i = start; i < max; i += incr) {
    float f = *(float *)&i;

    // PrintBinary(i);

    float exp = Cordic_exp(f);

    mantissaTable[index++] = exp;
    // versat_printf("%d %f %e\n",index,f,exp);
  }
}
#endif

typedef struct {
  u32 sign;
  u32 exp;
  u32 frac;
} ExpIndex;

ExpIndex Test(float n, int fractionalPrecision) {
  float data = n;

  int expPrecision = 8;
  int halfExpPrecision = expPrecision - 1;
  int expMax = (1 << halfExpPrecision) - 1;

  int asInteger = (int)data;
  int realPart = asInteger;
  if (realPart >= expMax) {
    realPart = expMax;
  }
  if (realPart <= -expMax) {
    realPart = -expMax;
  }

  bool isNegative = false;
  if (data < 0.0) {
    realPart = -realPart;
    isNegative = true;
    data = -data;
  }

  // NOTE: If the realPart goes outside the [-127,127] range, then
  //       we do not actually care about the fractional part since we are in the
  //       range of infinity anyway.

  // Should be between 0 and 1
  float asFraction = data - (float)realPart;
  u32 mantissaPartU32 = *((u32 *)&asFraction);

  UnpackedFP unpacked = Unpack(asFraction, true);

  u32 test = (unpacked.mantissa >>
              (8 + (16 - fractionalPrecision) - unpacked.exponent)) &
             ((1 << fractionalPrecision) - 1);

  // versat_printf("%d %02x %03x\n",isNegative,realPart,test);

  ExpIndex res = {isNegative ? 1 : 0, realPart, test};
  return res;
}

float InverseTest(ExpIndex in, int fractionalPrecision) {
  u32 fullMantissa = in.frac << (8 + (16 - fractionalPrecision));

  u32 exponent = 0;
  while (fullMantissa >= (1 << 24)) {
    fullMantissa /= 2;
    exponent += 1;
  }
  while (fullMantissa < (1 << 23)) {
    fullMantissa *= 2;
    exponent -= 1;
  }

  // versat_printf("%04x %04x\n",exponent,fullMantissa);

  UnpackedFP res = {};
  res.mantissa = fullMantissa;
  res.exponent = exponent;
  res.sign = in.sign;

  float f = Pack(res);
  return f;
}

static float new_expTable[256]; // left most bit is signal bit.
static float new_mantissaTable[1 << 13];
int fractionalPrecision = 12;

float newExp(float n) {
  float data = n;

  int expPrecision = 8;
  int halfExpPrecision = expPrecision - 1;
  int expMax = (1 << halfExpPrecision) - 1;

  // Hardware unit that calculates real part and also returns a floating point
  // "view" of the real part.
  int asInteger = (int)data;
  int realPart = asInteger;
  if (realPart >= expMax) {
    realPart = expMax;
  }
  if (realPart <= -expMax) {
    realPart = -expMax;
  }

  bool isNegative = false;
  if (data < 0.0) {
    realPart = -realPart;
    isNegative = true;
    data = -data;
  }

  // NOTE: If the realPart goes is outside the [-127,127] range, then
  //       we do not actually care about the fractional part since we are in the
  //       range of infinity anyway.

  // Should be between 0 and 1
  float asFraction = data - (float)realPart;
  u32 mantissaPartU32 = *((u32 *)&asFraction);

  UnpackedFP unpacked = Unpack(asFraction, true);

  // Hardware unit that performs this calculation and outputs the fracIndex.
  u32 fracIndex = (unpacked.mantissa >>
                   (8 + (16 - fractionalPrecision) - unpacked.exponent)) &
                  ((1 << fractionalPrecision) - 1);
  u32 expIndex = realPart + (isNegative ? 128 : 0);

  if (isNegative) {
    fracIndex += (1 << fractionalPrecision);
  }

  float exp = new_expTable[expIndex];
  float frac = new_mantissaTable[fracIndex];

  float res = exp * frac;

  return res;
}

float soft_logMantissaTable[1 << 13];

u32 LogCalculateIndex(UnpackedFP unpacked) {
  // Hardcoded for a fractional precision of 12
  u32 fracIndex = (unpacked.mantissa >> 11);

  return fracIndex;
}

float log2Value = 0.0f;
float tableLog(float in) {
  UnpackedFP unpacked = Unpack(in, false);

  float exp = (float)unpacked.exponent;
  u32 fracIndex = LogCalculateIndex(unpacked);

  float logMantissa = soft_logMantissaTable[fracIndex];
  float result = exp * log2Value + logMantissa;

  // versat_printf("A: %f %f %f %03x %f\n",in,
  // exp,log2Value,fracIndex,logMantissa);

  return result;
}

void testLog(float in) {
  float tableVal = tableLog(in);
  float realVal = Cordic_log(in);

  versat_printf("%f %f %f\n", tableVal, realVal, realVal - tableVal);
}

#define USE_CORDIC
#define USE_TABLE

#ifdef USE_TABLE
#define SOFT_POW(B, E) Cordic_pow(B, E)
#define SOFT_LOG(X) Cordic_log(X)
#define SOFT_EXP(X) newExp(X)
#elif USE_CORDIC
#define SOFT_POW(B, E) Cordic_pow(B, E)
#define SOFT_LOG(X) Cordic_log(X)
#define SOFT_EXP(X) Cordic_exp(X)
#else
#define SOFT_POW(B, E) my_pow(B, E)
#define SOFT_LOG(X) my_log(X)
#define SOFT_EXP(X) my_exp(X)
#endif

void *Software_Softmax(void *input, void *output, int index,
                       SoftmaxInfo *info) {
  float *view = (float *)input;
  float *out = (float *)output;

#if 0
  float sum = 0.0f;

  {
    u32 increment = 0x00000800; // For a fractionalPrecision of 12
    // float incr = 1.0 / (float)(1 << fractionalPrecision);
    float val = 1.0f;
    for (int i = 0; i < (1 << fractionalPrecision); i++) {
      soft_logMantissaTable[i] = Cordic_log(val);

      UnpackedFP unpacked = Unpack(val, false);
      u32 fracIndex = LogCalculateIndex(unpacked);
      UnpackedFP unpacked2 = Unpack(val + 1.0f, false);
      u32 fracIndex2 = LogCalculateIndex(unpacked2);
      UnpackedFP unpacked3 = Unpack(val - 1.0f, false);
      u32 fracIndex3 = LogCalculateIndex(unpacked3);

      versat_printf("%08x\n",*((u32*) &soft_logMantissaTable[i]));

#if 0
      versat_printf("%x %x %x %f %f\n", fracIndex, fracIndex2, fracIndex3, val,
                    soft_logMantissaTable[i]);
#endif

      u32 asU32 = *((u32 *)&val);
      asU32 += increment;

      val = *((float *)&asU32);
    }
    log2Value = Cordic_log(2.0f);
  }

  if (0) {
    // Test logarithm table approach
    float test = 1.5f;
    float expected = Cordic_log(test);

    float log2 = Cordic_log(2.0f);

    UnpackedFP unpack = Unpack(test, false);

    float exp = (float)unpack.exponent;

    unpack.exponent = 0;

    float mantissa = (float)Pack(unpack);
    float logMantissa = Cordic_log(mantissa);

    float result = exp * log2 + logMantissa;
    versat_printf("A: %f %f\n", exp, mantissa);
    versat_printf("B: %f %f\n", expected, result);
  }

#if 0
  versat_printf("%04x\n",CalculateFracIndex(Unpack(0.5f,false)));
  versat_printf("%04x\n",CalculateFracIndex(Unpack(1.5f,false)));
  versat_printf("%04x\n",CalculateFracIndex(Unpack(2.5f,false)));
  versat_printf("%04x\n",CalculateFracIndex(Unpack(3.5f,false)));
  versat_printf("%04x\n",CalculateFracIndex(Unpack(4.5f,false)));
#endif

  testLog(1024.4999f);
  testLog(1024.9999f);

#if 0
  testLog(0.5f);
  testLog(1.5f);
  testLog(2.5f);
  testLog(1.123f);
  testLog(1234.132f);
  testLog(0.00012f);
  testLog(0.000012f);
#endif

  return output;

  // Test exponential table approach
  // TODO: Changed the bias on the unpack stuff so this might start producing
  // wrong answers. Need to double check
#if 0
  float f = 0.0f;
  for (int i = 0; i < 128; i++) {
    new_expTable[i] = Cordic_exp(f);
    new_expTable[i + 128] = Cordic_exp(-f);
    f += 1.0f;
  }

  {
    float f = -89.2f;
    for (int i = 0; i < 200; i++) {
      ExpIndex t = Test(f, 12);

      int frac = t.frac;
      if (t.sign) {
        frac += (1 << (fractionalPrecision + 2));
      }

      versat_printf("%f %x %x\n", f, t.exp, frac);

      f += 1.0f;
    }
  }

  float incr = 1.0 / (float)(1 << fractionalPrecision);
  float p = incr;

  new_mantissaTable[0] = 1.0f;
  new_mantissaTable[(1 << fractionalPrecision)] = 1.0f;

  for (int i = 1; i < (1 << fractionalPrecision); i++) {
    new_mantissaTable[i] = Cordic_exp(p);
    new_mantissaTable[i + (1 << fractionalPrecision)] = Cordic_exp(-p);
    p += incr;
  }

#if 0
  {
    int fractionalPrecision = 10;
    float incr = 1.0 / (float) (1 << fractionalPrecision);
    float p = incr;
    for(int i = 1; i < (1 << fractionalPrecision); i++){
      ExpIndex t = Test(p,fractionalPrecision);
      float f = InverseTest(t,fractionalPrecision);
      //versat_printf("%x %x %x %f %f\n",t.sign,t.exp,t.frac, p,f);
      versat_printf("%f\n",p - f);

      new_mantissaTable[i] = exp(p);

      p += incr;
    }
    versat_printf("Finish\n");
  }

#endif

#if 0
  Test(2.999999);
  Test(2.8);
  Test(2.7);
  Test(2.6);
  Test(2.5);
  Test(2.4);
  Test(2.3);
  Test(2.2);
  Test(2.1);
  Test(2.05);
  Test(2.004);
  Test(2.0000001);
#endif

#if 0
  Test(2.999995);
  Test(2.75);
  Test(2.5);
  Test(2.25);
  Test(2.0);
  Test(1.0);
  Test(0.5);
  Test(0.0);
  Test(-0.00001);
  Test(-0.5);
  Test(-1.0);
  Test(-2.0);
#endif

  // return output;
#endif

  /*
  Gonna test 8 bits for real part. (1 sign + 7 actual bits)
  Gonna test 16 bits for fractional part.
  */

#if 0
  InitializeExpTable();
#endif
#endif

  // Axis are normalized here, no need to handle negative axis after this point
  int axis = info->axis;
  if (axis < 0) {
    axis += info->numberInputDims;
  }

  /*
    The idea behind the softmax axis is that we separate dimensions into two
    regions One is the iteration region and the other is the value region. The
    axis is the separator and the dims to the right and including the axis are
    the value region. For an axis of 0, the value region is everything so we sum
    everything and calculate softmax. We do 1 sum in this mode. For an axis of
    1, the iteration region is a single loop and the rest is sum and used to
    calculate softmax. Note that if the iteration region contains a loop of size
    N we do N total sums. For an axis of 2 the iteration region is two loops. If
    we have loop of size N and M then we calculate N*M total sums. And so on.
  */

  // TODO: We probably can simplify the logic in here by using Dimensions.

  AddressGen testInst =
      StartAddress(info->inputDims, info->inputDims, info->numberInputDims);
  AddressGen *test = &testInst;

  int kernelSize = info->numberInputDims - axis;

  for (; Address_IsValid(test); Address_AdvanceAxis(test, axis - 1)) {
    int kernelDims[MAX_DIMS] = {};
    for (int i = 0; i < kernelSize; i++) {
      kernelDims[i] = info->inputDims[i + axis];
    }

    float sum = 0.0f;

    KernelGen genInst = StartKernel(test, kernelDims, kernelSize);
    KernelGen *gen = &genInst;
    for (; Kernel_IsValid(gen); Kernel_Advance(gen)) {
      int index = Kernel_GetValue(gen);

      out[index] = SOFT_EXP(view[index]);
      sum += out[index];
    }

    genInst = StartKernel(test, kernelDims, kernelSize);
    for (; Kernel_IsValid(gen); Kernel_Advance(gen)) {
      int index = Kernel_GetValue(gen);

      out[index] = out[index] / sum;
    }
  }

  return output;
}

// TODO: While this is the approach that directly matches what ONNX requires, it
// is also slower for the average case. (Where the statistic values are usually
// initializers and not inputs.)
//       A lot of the logic can be simplified by precomputing values (ex: the
//       invsqrt routine is not needed since it only cares about values that we
//       already know about) This of course can only be perform if the values
//       are initializers and not inputs. (Which I assume is the default case
//       for a great deal of these.) That means there is a possibility of using
//       a much faster routine by pushing logic to the onnx converter and have
//       it collapse all the initializers into a simpler operation.
void *Software_BatchNormalization(void *inputX, void *scale, void *inputB,
                                  void *mean, void *var, void *output,
                                  int index, BatchNormalizationInfo *info) {

  float *x = (float *)inputX;
  float *s = (float *)scale;
  float *b = (float *)inputB;
  float *m = (float *)mean;
  float *v = (float *)var;
  float *o = (float *)output;

  Dimensions dim = CreateDimensions(info->inputDims, info->numberInputDims);

  if (dim.size <= 1) {
    Dimensions_AppendInPlace(&dim, 1);
  }

  AddressGen addrInst = StartAddressFromDims(dim, 2);
  AddressGen *addr = &addrInst;

  // TODO: We probably can also do this using the Kernel stuff.
  //       But I kinda want a better interface when using kernel stuff.
  Dimensions leftover = Dimensions_Cut_GetRight(dim, 2);
  int size = Dimensions_TotalSize(leftover);

  while (Address_IsValid(addr)) {
    int c = Address_GetDim(addr, 1);

    int index = Address_GetValue(addr);

    for (int i = 0; i < size; i++) {
      o[index + i] =
          ((x[index + i] - m[c]) * my_invsqrt(v[c] + info->epsilon)) * s[c] +
          b[c];
    }

    Address_Advance(addr);
  }

  return o;
}

void *Software_Dropout(void *input, void *out, int index, DropoutInfo *info) {
  // TODO: Need to copy the input, cannot assume that memory will remain valid.
  // NOTE: If we want to avoid the copy need to put logic on onnx script that
  // removes the operator call.
  return input;
}

void *Software_LRN(void *input, void *out, int index, LRNInfo *info) {
  int N = info->inputDims[0];
  int C = info->inputDims[1];
  int Y = info->inputDims[2];
  int X = info->inputDims[3];

  int n = info->size;
  double k = (double)info->bias;
  double a = (double)info->alpha;
  double b = (double)info->beta;

  float *in = (float *)input;
  float *output = (float *)out;

  AddressGen addrInst =
      StartAddress(info->inputDims, info->inputDims, info->numberInputDims);
  AddressGen *addr = &addrInst;
  int loopCount = 0;
  for (; Address_IsValid(addr); Address_Advance(addr)) {
    int c = Address_GetDim(addr, 1);

    int lowerBound = MAX(0, c - n / 2);
    int upperBound = MIN(C - 1, c + n / 2);

    KernelGen genInst =
        StartKernel_IterateOneDimOnly(addr, 1, lowerBound, upperBound + 1);
    KernelGen *gen = &genInst;

    double sum = 0.0f;
    for (; Kernel_IsValid(gen); Kernel_Advance(gen)) {
      int index = Kernel_GetValue(gen);

      double val = (double)in[index];

      sum += (val * val);
    }

    int index = Address_GetValue(addr);

    double div = SOFT_POW(k + (a / n) * sum, b);
    output[index] = (((double)in[index]) / div);
  }

  return output;
}

void *Software_Gemm(void *inA, void *inB, void *inC, void *out, int index,
                    GemmInfo *info) {
  // TODO: Implement this.
  return out;
}
