// File generated by onnxMain.py.
// Do not modify
#ifndef VERSAT_AI_OPERATORS_META
#define VERSAT_AI_OPERATORS_META

typedef enum {
  OperatorType_Add = 0,
  OperatorType_Relu = 1,
  OperatorType_MaxPool = 2,
  OperatorType_AveragePool = 3,
  OperatorType_Conv = 4,
  OperatorType_Reshape = 5,
  OperatorType_MatMul = 6,
  OperatorType_Softmax = 7,
  OperatorType_Transpose = 8,
  OperatorType_BatchNormalization = 9,
  OperatorType_Dropout = 10,
  OperatorType_LRN = 11,
  OperatorType_Gemm = 12
} OperatorType;

static inline char *VERSAT_OperatorName(int opType, int useVersat) {
  switch (opType) {
  case 0: {
    if (useVersat) {
      return "Versat_Add";
    } else {
      return "Soft_Add";
    }
  } break;
  case 1: {
    if (useVersat) {
      return "Versat_Relu";
    } else {
      return "Soft_Relu";
    }
  } break;
  case 2: {
    if (useVersat) {
      return "Versat_MaxPool";
    } else {
      return "Soft_MaxPool";
    }
  } break;
  case 3: {
    if (useVersat) {
      return "Versat_AveragePool";
    } else {
      return "Soft_AveragePool";
    }
  } break;
  case 4: {
    if (useVersat) {
      return "Versat_Conv";
    } else {
      return "Soft_Conv";
    }
  } break;
  case 5: {
    if (useVersat) {
      return "Versat_Reshape";
    } else {
      return "Soft_Reshape";
    }
  } break;
  case 6: {
    if (useVersat) {
      return "Versat_MatMul";
    } else {
      return "Soft_MatMul";
    }
  } break;
  case 7: {
    if (useVersat) {
      return "Versat_Softmax";
    } else {
      return "Soft_Softmax";
    }
  } break;
  case 8: {
    if (useVersat) {
      return "Versat_Transpose";
    } else {
      return "Soft_Transpose";
    }
  } break;
  case 9: {
    if (useVersat) {
      return "Versat_BatchNormalization";
    } else {
      return "Soft_BatchNormalization";
    }
  } break;
  case 10: {
    if (useVersat) {
      return "Versat_Dropout";
    } else {
      return "Soft_Dropout";
    }
  } break;
  case 11: {
    if (useVersat) {
      return "Versat_LRN";
    } else {
      return "Soft_LRN";
    }
  } break;
  case 12: {
    if (useVersat) {
      return "Versat_Gemm";
    } else {
      return "Soft_Gemm";
    }
  } break;
    return "";
  }
}

typedef enum {
  PaddingType_NOTSET = 0,
  PaddingType_SAME_UPPER = 1,
  PaddingType_SAME_LOWER = 2,
  PaddingType_VALID = 3
} PaddingType;

typedef struct {
  int maxDims;
  // Followed by
  // int64_t firstInputDims[maxDims];
  // int64_t secondInputDims[maxDims];
  // int64_t broadCastedShape[maxDims];
} AddInfo;

#define VERSAT_AddInfo_firstInputDims(INFO)                                    \
  ((int64_t *)VERSAT_OFFSET_PTR(INFO, sizeof(AddInfo)))
#define VERSAT_AddInfo_secondInputDims(INFO)                                   \
  ((int64_t *)VERSAT_OFFSET_PTR(VERSAT_AddInfo_firstInputDims(INFO),           \
                                INFO->maxDims * sizeof(int64_t)))
#define VERSAT_AddInfo_broadCastedShape(INFO)                                  \
  ((int64_t *)VERSAT_OFFSET_PTR(VERSAT_AddInfo_secondInputDims(INFO),          \
                                INFO->maxDims * sizeof(int64_t)))

typedef struct {
  int dims;
  // Followed by
  // int64_t inputDims[dims];
} ReluInfo;

#define VERSAT_ReluInfo_inputDims(INFO)                                        \
  ((int64_t *)VERSAT_OFFSET_PTR(INFO, sizeof(ReluInfo)))

typedef struct {
  int dims;
  int kernelSize;
  int strideSize;
  int padsSize;
  PaddingType padding;
  // Followed by
  // int kernelDims[kernelSize];
  // int strideDims[strideSize];
  // int padsDims[padsSize];
  // int64_t inputDims[dims];
  // int64_t outputDims[dims];
} MaxPoolInfo;

#define VERSAT_MaxPoolInfo_kernelDims(INFO)                                    \
  ((int *)VERSAT_OFFSET_PTR(INFO, sizeof(MaxPoolInfo)))
#define VERSAT_MaxPoolInfo_strideDims(INFO)                                    \
  ((int *)VERSAT_OFFSET_PTR(VERSAT_MaxPoolInfo_kernelDims(INFO),               \
                            INFO->kernelSize * sizeof(int)))
#define VERSAT_MaxPoolInfo_padsDims(INFO)                                      \
  ((int *)VERSAT_OFFSET_PTR(VERSAT_MaxPoolInfo_strideDims(INFO),               \
                            INFO->strideSize * sizeof(int)))
#define VERSAT_MaxPoolInfo_inputDims(INFO)                                     \
  ((int64_t *)VERSAT_OFFSET_PTR(VERSAT_MaxPoolInfo_padsDims(INFO),             \
                                INFO->padsSize * sizeof(int)))
#define VERSAT_MaxPoolInfo_outputDims(INFO)                                    \
  ((int64_t *)VERSAT_OFFSET_PTR(VERSAT_MaxPoolInfo_inputDims(INFO),            \
                                INFO->dims * sizeof(int64_t)))

typedef struct {
  int dims;
  int kernelSize;
  int strideSize;
  int padsSize;
  PaddingType padding;
  // Followed by
  // int kernelDims[kernelSize];
  // int strideDims[strideSize];
  // int padsDims[padsSize];
  // int64_t inputDims[dims];
  // int64_t outputDims[dims];
} AveragePoolInfo;

#define VERSAT_AveragePoolInfo_kernelDims(INFO)                                \
  ((int *)VERSAT_OFFSET_PTR(INFO, sizeof(AveragePoolInfo)))
#define VERSAT_AveragePoolInfo_strideDims(INFO)                                \
  ((int *)VERSAT_OFFSET_PTR(VERSAT_AveragePoolInfo_kernelDims(INFO),           \
                            INFO->kernelSize * sizeof(int)))
#define VERSAT_AveragePoolInfo_padsDims(INFO)                                  \
  ((int *)VERSAT_OFFSET_PTR(VERSAT_AveragePoolInfo_strideDims(INFO),           \
                            INFO->strideSize * sizeof(int)))
#define VERSAT_AveragePoolInfo_inputDims(INFO)                                 \
  ((int64_t *)VERSAT_OFFSET_PTR(VERSAT_AveragePoolInfo_padsDims(INFO),         \
                                INFO->padsSize * sizeof(int)))
#define VERSAT_AveragePoolInfo_outputDims(INFO)                                \
  ((int64_t *)VERSAT_OFFSET_PTR(VERSAT_AveragePoolInfo_inputDims(INFO),        \
                                INFO->dims * sizeof(int64_t)))

typedef struct {
  int dims;
  int group;
  int featureMaps;
  int kernelSize;
  int strideSize;
  int dilationsSize;
  int padsSize;
  PaddingType padding;
  // Followed by
  // int kernelDims[kernelSize];
  // int strideDims[strideSize];
  // int dilationsDims[dilationsSize];
  // int padsDims[padsSize];
  // int64_t inputDims[dims];
  // int64_t outputDims[dims];
} ConvInfo;

#define VERSAT_ConvInfo_kernelDims(INFO)                                       \
  ((int *)VERSAT_OFFSET_PTR(INFO, sizeof(ConvInfo)))
#define VERSAT_ConvInfo_strideDims(INFO)                                       \
  ((int *)VERSAT_OFFSET_PTR(VERSAT_ConvInfo_kernelDims(INFO),                  \
                            INFO->kernelSize * sizeof(int)))
#define VERSAT_ConvInfo_dilationsDims(INFO)                                    \
  ((int *)VERSAT_OFFSET_PTR(VERSAT_ConvInfo_strideDims(INFO),                  \
                            INFO->strideSize * sizeof(int)))
#define VERSAT_ConvInfo_padsDims(INFO)                                         \
  ((int *)VERSAT_OFFSET_PTR(VERSAT_ConvInfo_dilationsDims(INFO),               \
                            INFO->dilationsSize * sizeof(int)))
#define VERSAT_ConvInfo_inputDims(INFO)                                        \
  ((int64_t *)VERSAT_OFFSET_PTR(VERSAT_ConvInfo_padsDims(INFO),                \
                                INFO->padsSize * sizeof(int)))
#define VERSAT_ConvInfo_outputDims(INFO)                                       \
  ((int64_t *)VERSAT_OFFSET_PTR(VERSAT_ConvInfo_inputDims(INFO),               \
                                INFO->dims * sizeof(int64_t)))

typedef struct {
  int numberInputDims;
  int numberShapeDims;
  // Followed by
  // int64_t inputDims[numberInputDims];
} ReshapeInfo;

#define VERSAT_ReshapeInfo_inputDims(INFO)                                     \
  ((int64_t *)VERSAT_OFFSET_PTR(INFO, sizeof(ReshapeInfo)))

typedef struct {
  int numberInputADims;
  int numberInputBDims;
  int numberOutputDims;
  // Followed by
  // int64_t inputADims[numberInputADims];
  // int64_t inputBDims[numberInputBDims];
  // int64_t outputDims[numberOutputDims];
} MatMulInfo;

#define VERSAT_MatMulInfo_inputADims(INFO)                                     \
  ((int64_t *)VERSAT_OFFSET_PTR(INFO, sizeof(MatMulInfo)))
#define VERSAT_MatMulInfo_inputBDims(INFO)                                     \
  ((int64_t *)VERSAT_OFFSET_PTR(VERSAT_MatMulInfo_inputADims(INFO),            \
                                INFO->numberInputADims * sizeof(int64_t)))
#define VERSAT_MatMulInfo_outputDims(INFO)                                     \
  ((int64_t *)VERSAT_OFFSET_PTR(VERSAT_MatMulInfo_inputBDims(INFO),            \
                                INFO->numberInputBDims * sizeof(int64_t)))

typedef struct {
  int numberInputDims;
  int axis;
  // Followed by
  // int64_t inputDims[numberInputDims];
} SoftmaxInfo;

#define VERSAT_SoftmaxInfo_inputDims(INFO)                                     \
  ((int64_t *)VERSAT_OFFSET_PTR(INFO, sizeof(SoftmaxInfo)))

typedef struct {
  int numberInputDims;
  int permSize;
  // Followed by
  // int64_t inputDims[numberInputDims];
  // int64_t perm[permSize];
} TransposeInfo;

#define VERSAT_TransposeInfo_inputDims(INFO)                                   \
  ((int64_t *)VERSAT_OFFSET_PTR(INFO, sizeof(TransposeInfo)))
#define VERSAT_TransposeInfo_perm(INFO)                                        \
  ((int64_t *)VERSAT_OFFSET_PTR(VERSAT_TransposeInfo_inputDims(INFO),          \
                                INFO->numberInputDims * sizeof(int64_t)))

typedef struct {
  int numberInputDims;
  float epsilon;
  float momentum;
  // Followed by
  // int64_t inputDims[numberInputDims];
} BatchNormalizationInfo;

#define VERSAT_BatchNormalizationInfo_inputDims(INFO)                          \
  ((int64_t *)VERSAT_OFFSET_PTR(INFO, sizeof(BatchNormalizationInfo)))

typedef struct {
  int numberInputDims;
  float ratio;
  // Followed by
  // int64_t inputDims[numberInputDims];
} DropoutInfo;

#define VERSAT_DropoutInfo_inputDims(INFO)                                     \
  ((int64_t *)VERSAT_OFFSET_PTR(INFO, sizeof(DropoutInfo)))

typedef struct {
  int numberInputDims;
  float alpha;
  float beta;
  float bias;
  int size;
  // Followed by
  // int64_t inputDims[numberInputDims];
} LRNInfo;

#define VERSAT_LRNInfo_inputDims(INFO)                                         \
  ((int64_t *)VERSAT_OFFSET_PTR(INFO, sizeof(LRNInfo)))

typedef struct {
  int numberInputDims;
  float alpha;
  float beta;
  int transA;
  int transB;
  // Followed by
  // int64_t aDims[numberInputDims];
  // int64_t bDims[numberInputDims];
  // int64_t cDims[numberInputDims];
} GemmInfo;

#define VERSAT_GemmInfo_aDims(INFO)                                            \
  ((int64_t *)VERSAT_OFFSET_PTR(INFO, sizeof(GemmInfo)))
#define VERSAT_GemmInfo_bDims(INFO)                                            \
  ((int64_t *)VERSAT_OFFSET_PTR(VERSAT_GemmInfo_aDims(INFO),                   \
                                INFO->numberInputDims * sizeof(int64_t)))
#define VERSAT_GemmInfo_cDims(INFO)                                            \
  ((int64_t *)VERSAT_OFFSET_PTR(VERSAT_GemmInfo_bDims(INFO),                   \
                                INFO->numberInputDims * sizeof(int64_t)))

#endif // VERSAT_AI_OPERATORS_META